// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Errors {
    error RevertCode(Code errorCode);

    enum Code {
        COMPTROLLER_HALTED, // 0: "Halted"
        COMPTROLLER_BANNED, // 1: "Banned"
        COMPTROLLER_ZERO_ADDRESS, // 2: "Zero address"
        COMPTROLLER_TOS_AND_SIGS_LENGTH_INCONSISTENT, // 3: "tos and sigs length are inconsistent"
        COMPTROLLER_DENOMINATIONS_AND_DUSTS_LENGTH_INCONSISTENT, // 4: "denominations and dusts length are inconsistent"
        MORTGAGE_VAULT_FUND_MORTGAGED, // 5: "Fund mortgaged"
        SHARE_TOKEN_INVALID_TO, // 6: "Invalid to"
        IMPLEMENTATION_ASSET_LIST_NOT_EMPTY, // 7: "assetList is not empty"
        IMPLEMENTATION_PENDING_NOT_START, // 8: "Pending does not start"
        IMPLEMENTATION_PENDING_NOT_EXPIRE, // 9: "Pending does not expire"
        BLANK_10, // 10: ""
        IMPLEMENTATION_INVALID_ASSET, // 11: "Invalid asset"
        IMPLEMENTATION_INVALID_DENOMINATION, // 12: "Invalid denomination"
        FUND_PROXY_FACTORY_INVALID_CREATOR, // 13: "Invalid creator"
        FUND_PROXY_STORAGE_UTILS_IS_NOT_ZERO, // 14: "Is not zero value or address "
        FUND_PROXY_STORAGE_UTILS_IS_ZERO, // 15: "Is zero value or address"
        BLANK_16, // 16: ""
        BLANK_17, // 17: ""
        FUND_PROXY_STORAGE_UTILS_INVALID_DENOMINATION, // 18: "Invalid denomination"
        BLANK_19, // 19: ""
        BLANK_20, // 20: ""
        BLANK_21, // 21: ""
        BLANK_22, // 22: ""
        BLANK_23, // 23: ""
        BLANK_24, // 24: ""
        BLANK_25, // 25: ""
        BLANK_26, // 26: ""
        BLANK_27, // 27: ""
        FUND_PROXY_STORAGE_UTILS_WRONG_ALLOWANCE, // 28: "Wrong allowance"
        TASK_EXECUTOR_TOS_AND_DATAS_LENGTH_INCONSISTENT, // 29: "tos and datas length inconsistent"
        TASK_EXECUTOR_TOS_AND_CONFIGS_LENGTH_INCONSISTENT, // 30: "tos and configs length inconsistent"
        TASK_EXECUTOR_INVALID_COMPTROLLER_DELEGATE_CALL, // 31: "Invalid comptroller delegate call"
        TASK_EXECUTOR_INVALID_COMPTROLLER_CONTRACT_CALL, // 32: "Invalid comptroller contract call"
        TASK_EXECUTOR_INVALID_DEALING_ASSET, // 33: "Invalid dealing asset"
        TASK_EXECUTOR_REFERENCE_TO_OUT_OF_LOCALSTACK, // 34: "Reference to out of localStack"
        TASK_EXECUTOR_RETURN_NUM_AND_PARSED_RETURN_NUM_NOT_MATCHED, // 35: "Return num and parsed return num not matched"
        TASK_EXECUTOR_ILLEGAL_LENGTH_FOR_PARSE, // 36: "Illegal length for _parse"
        TASK_EXECUTOR_STACK_OVERFLOW, // 37: "Stack overflow"
        TASK_EXECUTOR_INVALID_INITIAL_ASSET, // 38: "Invalid initial asset"
        TASK_EXECUTOR_NON_ZERO_QUOTA, // 39: "Quota is not zero"
        AFURUCOMBO_TOKENS_AND_AMOUNTS_LENGTH_INCONSISTENT, // 40: "Token length != amounts length"
        AFURUCOMBO_INVALID_COMPTROLLER_HANDLER_CALL, // 41: "Invalid comptroller handler call"
        BLANK_42, // 42: ""
        CHAINLINK_ASSETS_AND_AGGREGATORS_INCONSISTENT, // 43: "assets.length == aggregators.length"
        CHAINLINK_ZERO_ADDRESS, // 44: "Zero address"
        CHAINLINK_EXISTING_ASSET, // 45: "Existing asset"
        CHAINLINK_NON_EXISTENT_ASSET, // 46: "Non-existent asset"
        CHAINLINK_INVALID_PRICE, // 47: "Invalid price"
        CHAINLINK_STALE_PRICE, // 48: "Stale price"
        ASSET_ROUTER_ASSETS_AND_AMOUNTS_LENGTH_INCONSISTENT, // 49: "assets length != amounts length"
        ASSET_ROUTER_NEGATIVE_VALUE, // 50: "Negative value"
        ASSET_REGISTRY_ZERO_RESOLVER_ADDRESS, // 51: "Resolver zero address"
        ASSET_REGISTRY_ZERO_ASSET_ADDRESS, // 52: "Asset zero address"
        ASSET_REGISTRY_BANNED_RESOLVER, // 53: "Resolver has been banned"
        ASSET_REGISTRY_REGISTERED_RESOLVER, // 54: "Resolver is registered"
        ASSET_REGISTRY_NON_REGISTERED_RESOLVER, // 55: "Asset not registered"
        ASSET_REGISTRY_NON_BANNED_RESOLVER, // 56: "Resolver is not banned"
        ASSET_REGISTRY_UNREGISTERED, // 57: "Unregistered"
        BLANK_58, // 58: ""
        RCURVE_STABLE_ZERO_ASSET_ADDRESS, // 59: "Zero asset address"
        RCURVE_STABLE_ZERO_POOL_ADDRESS, // 60: "Zero pool address"
        RCURVE_STABLE_ZERO_VALUED_ASSET_ADDRESS, // 61: "Zero valued asset address"
        RCURVE_STABLE_VALUED_ASSET_DECIMAL_NOT_MATCH_VALUED_ASSET, // 62: "Valued asset decimal not match valued asset"
        RCURVE_STABLE_POOL_INFO_IS_NOT_SET, // 63: "Pool info is not set"
        ASSET_MODULE_DIFFERENT_ASSET_REMAINING, // 64: "Different asset remaining"
        PERFORMANCE_FEE_MODULE_FEE_RATE_SHOULD_BE_LESS_THAN_BASE, // 65: "Fee rate should be less than 100%"
        PERFORMANCE_FEE_MODULE_CRYSTALLIZATION_PERIOD_TOO_SHORT, // 66: "Crystallization period too short"
        PERFORMANCE_FEE_MODULE_CAN_NOT_CRYSTALLIZED_YET, // 67: "Can not crystallized yet"
        PERFORMANCE_FEE_MODULE_TIME_BEFORE_START, // 68: "Time before start"
        MANAGEMENT_FEE_MODULE_FEE_RATE_SHOULD_BE_LESS_THAN_FUND_BASE, // 69: "Fee rate should be less than 100%"
        SHARE_MODULE_REDEEM_IN_PENDING_WITHOUT_PERMISSION, // 70: "Redeem in pending without permission"
        AFURUCOMBO_REMAINING_TOKENS, // 71: "Furucombo has remaining tokens"
        IMPLEMENTATION_PENDING_SHARE_NOT_RESOLVABLE, // 72: "pending share is not resolvable"
        IMPLEMENTATION_INSUFFICIENT_TOTAL_VALUE_FOR_EXECUTION, // 73: "Insufficient total value for execution"
        SHARE_MODULE_INSUFFICIENT_SHARE, // 74: "Insufficient share amount"
        FUND_PROXY_FACTORY_INVALID_MORTGAGE_TIER, // 75: "Mortgage tier not set in comptroller"
        BLANK_76, // 76: ""
        SHARE_MODULE_PENDING_REDEMPTION_NOT_CLAIMABLE, // 77: "Pending redemption is not claimable"
        SHARE_MODULE_PENDING_ROUND_INCONSISTENT, // 78: "user pending round and current pending round are inconsistent"
        FUND_PROXY_FACTORY_INVALID_DENOMINATION, // 79: "Invalid denomination"
        SHARE_MODULE_SHARE_AMOUNT_TOO_LARGE, // 80: "The requesting share amount is greater than total share amount"
        SHARE_MODULE_PURCHASE_ZERO_BALANCE, // 81: "The purchased balance is zero"
        SHARE_MODULE_PURCHASE_ZERO_SHARE, // 82: "The share purchased need to greater than zero"
        SHARE_MODULE_REDEEM_ZERO_SHARE, // 83: "The redeem share is zero"
        SHARE_TOKEN_INVALID_FROM, // 84: "Invalid from"
        IMPLEMENTATION_INVALID_MORTGAGE_TIER, // 85: "Mortgage tier not set in comptroller"
        AFURUCOMBO_DUPLICATED_TOKENSOUT, // 86: "Duplicated tokensOut"
        FUND_PROXY_STORAGE_UTILS_UNKNOWN_OWNER, // 87: "Unknown owner"
        ASSET_MODULE_FULL_ASSET_CAPACITY, // 88: "Full Asset Capacity"
        COMPTROLLER_BEACON_IS_INITIALIZED, // 89: "Beacon is initialized"
        RESOLVER_ASSET_VALUE_NEGATIVE, // 90: "Resolver's asset value < 0"
        RESOLVER_ASSET_VALUE_POSITIVE // 91: "Resolver's asset value > 0"
    }

    function _require(bool condition_, Code errorCode_) internal pure {
        if (!condition_) revert RevertCode(errorCode_);
    }

    function _revertMsg(string memory functionName_, string memory reason_) internal pure {
        revert(string(abi.encodePacked(functionName_, ": ", reason_)));
    }

    function _revertMsg(string memory functionName_) internal pure {
        _revertMsg(functionName_, "Unspecified");
    }
}
